In [2]:
import torch

In [3]:
x = torch.rand(3)

In [4]:
print(x)

tensor([0.2259, 0.3773, 0.4407])


In [11]:
x2= torch.empty(2,3,4)

In [12]:
print(x2)

tensor([[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00, -2.0000e+00,  0.0000e+00, -2.0000e+00],
         [ 1.2612e-44,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00, -2.0000e+00, -5.2080e+15, -2.0005e+00],
         [ 2.8026e-45,  0.0000e+00,  0.0000e+00,  4.5918e-40]]])


In [16]:
x3 = torch.ones(2,3, dtype= torch.int32)

In [17]:
print(x3)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [18]:
print(x3.dtype)

torch.int32


In [20]:
x4 = torch.tensor([5.5, 3])
print(x.size())

torch.Size([2])
